name: metafy_edge_detection
description: A flutter plugin to detect edges of objects, scan paper, detect corner, detect rectangle. It allows cropping of the detected object image and returns the path of the cropped image.
version: 1.1.1
homepage: https://github.com/MaduraDiasTreinetic/metafy_edge_detection

environment:
  sdk: ">=2.17.6 <3.0.0" 
  flutter: ">=1.20.0"
  

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sample.edgedetection
        pluginClass: EdgeDetectionPlugin
      ios:
        pluginClass: EdgeDetectionPlugin
